/* File: lennard_jonesmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Mon Feb 16 19:59:39 2015
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *lennard_jones_error;
static PyObject *lennard_jones_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define PRINTPYOBJERR(obj)\
  fprintf(stderr,"lennard_jones.error is related to ");\
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");

#define pyobj_from_int1(v) (PyInt_FromLong(v))
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(lennard_jones_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(arr->data)=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(arr->data)=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: (arr->descr->f->setitem)(pyobj_from_ ## ctype ## 1(*v),arr->data); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (arr->descr->type==typecode)  {*(ctype *)(arr->data)=*v; return 1;}\
        switch (arr->descr->type_num) {\
                case NPY_DOUBLE: *(double *)(arr->data)=*v; break;\
                case NPY_INT: *(int *)(arr->data)=*v; break;\
                case NPY_LONG: *(long *)(arr->data)=*v; break;\
                case NPY_FLOAT: *(float *)(arr->data)=*v; break;\
                case NPY_CDOUBLE: *(double *)(arr->data)=*v; break;\
                case NPY_CFLOAT: *(float *)(arr->data)=*v; break;\
                case NPY_BOOL: *(npy_bool *)(arr->data)=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(arr->data)=*v; break;\
                case NPY_BYTE: *(signed char *)(arr->data)=*v; break;\
                case NPY_SHORT: *(short *)(arr->data)=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(arr->data)=*v; break;\
                case NPY_UINT: *(npy_uint *)(arr->data)=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(arr->data)=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(arr->data)=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(arr->data)=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(arr->data)=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(arr->data)=*v; break;\
                case NPY_OBJECT: (arr->descr->f->setitem)(pyobj_from_ ## ctype ## 1(*v),arr->data, arr); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int try_pyarr_from_int(PyObject* obj,int* v) {
  TRYPYARRAYTEMPLATE(int,'i');
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = lennard_jones_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = lennard_jones_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(lennard_jones,LENNARD_JONES)(double*,double*,double*,double*,double*,int*,int*,double*,double*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* lennard_jones *******************************/
static char doc_f2py_rout_lennard_jones_lennard_jones[] = "\
force,Ep = lennard_jones(r_min,eps,L,r_c,p,[N,d])\n\nWrapper for ``lennard_jones``.\
\n\nParameters\n----------\n"
"r_min : input float\n"
"eps : input float\n"
"L : input float\n"
"r_c : input float\n"
"p : input rank-2 array('d') with bounds (N,d)\n"
"\nOther Parameters\n----------------\n"
"N : in/output rank-0 array(int,'i'), optional\n    Default: shape(p,0)\n"
"d : in/output rank-0 array(int,'i'), optional\n    Default: shape(p,1)\n"
"\nReturns\n-------\n"
"force : rank-2 array('d') with bounds (N,d)\n"
"Ep : float";
/* extern void F_FUNC_US(lennard_jones,LENNARD_JONES)(double*,double*,double*,double*,double*,int*,int*,double*,double*); */
static PyObject *f2py_rout_lennard_jones_lennard_jones(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,double*,int*,int*,double*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double r_min = 0;
  PyObject *r_min_capi = Py_None;
  double eps = 0;
  PyObject *eps_capi = Py_None;
  double L = 0;
  PyObject *L_capi = Py_None;
  double r_c = 0;
  PyObject *r_c_capi = Py_None;
  double *p = NULL;
  npy_intp p_Dims[2] = {-1, -1};
  const int p_Rank = 2;
  PyArrayObject *capi_p_tmp = NULL;
  int capi_p_intent = 0;
  PyObject *p_capi = Py_None;
  int N = 0;
  PyObject *N_capi = Py_None;
  int d = 0;
  PyObject *d_capi = Py_None;
  double *force = NULL;
  npy_intp force_Dims[2] = {-1, -1};
  const int force_Rank = 2;
  PyArrayObject *capi_force_tmp = NULL;
  int capi_force_intent = 0;
  double Ep = 0;
  static char *capi_kwlist[] = {"r_min","eps","L","r_c","p","N","d",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OO:lennard_jones.lennard_jones",\
    capi_kwlist,&r_min_capi,&eps_capi,&L_capi,&r_c_capi,&p_capi,&N_capi,&d_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable r_c */
    f2py_success = double_from_pyobj(&r_c,r_c_capi,"lennard_jones.lennard_jones() 4th argument (r_c) can't be converted to double");
  if (f2py_success) {
  /* Processing variable r_min */
    f2py_success = double_from_pyobj(&r_min,r_min_capi,"lennard_jones.lennard_jones() 1st argument (r_min) can't be converted to double");
  if (f2py_success) {
  /* Processing variable eps */
    f2py_success = double_from_pyobj(&eps,eps_capi,"lennard_jones.lennard_jones() 2nd argument (eps) can't be converted to double");
  if (f2py_success) {
  /* Processing variable L */
    f2py_success = double_from_pyobj(&L,L_capi,"lennard_jones.lennard_jones() 3rd argument (L) can't be converted to double");
  if (f2py_success) {
  /* Processing variable p */
  ;
  capi_p_intent |= F2PY_INTENT_IN;
  capi_p_tmp = array_from_pyobj(NPY_DOUBLE,p_Dims,p_Rank,capi_p_intent,p_capi);
  if (capi_p_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(lennard_jones_error,"failed in converting 5th argument `p' of lennard_jones.lennard_jones to C/Fortran array" );
  } else {
    p = (double *)(capi_p_tmp->data);

  /* Processing variable Ep */
  /* Processing variable d */
  if (d_capi == Py_None) d = shape(p,1); else
    f2py_success = int_from_pyobj(&d,d_capi,"lennard_jones.lennard_jones() 2nd keyword (d) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(p,1)==d,"shape(p,1)==d","2nd keyword d","lennard_jones:d=%d",d) {
  /* Processing variable N */
  if (N_capi == Py_None) N = shape(p,0); else
    f2py_success = int_from_pyobj(&N,N_capi,"lennard_jones.lennard_jones() 1st keyword (N) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(p,0)==N,"shape(p,0)==N","1st keyword N","lennard_jones:N=%d",N) {
  /* Processing variable force */
  force_Dims[0]=N,force_Dims[1]=d;
  capi_force_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_force_tmp = array_from_pyobj(NPY_DOUBLE,force_Dims,force_Rank,capi_force_intent,Py_None);
  if (capi_force_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(lennard_jones_error,"failed in converting hidden `force' of lennard_jones.lennard_jones to C/Fortran array" );
  } else {
    force = (double *)(capi_force_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&r_min,&eps,&L,&r_c,p,&N,&d,force,&Ep);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_int(N_capi,&N);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(d_capi,&d);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Nd",capi_force_tmp,Ep);
/*closepyobjfrom*/
  } /*if (f2py_success) of d pyobjfrom*/
  } /*if (f2py_success) of N pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_force_tmp == NULL) ... else of force*/
  /* End of cleaning variable force */
  } /*CHECKSCALAR(shape(p,0)==N)*/
  } /*if (f2py_success) of N*/
  /* End of cleaning variable N */
  } /*CHECKSCALAR(shape(p,1)==d)*/
  } /*if (f2py_success) of d*/
  /* End of cleaning variable d */
  /* End of cleaning variable Ep */
  if((PyObject *)capi_p_tmp!=p_capi) {
    Py_XDECREF(capi_p_tmp); }
  }  /*if (capi_p_tmp == NULL) ... else of p*/
  /* End of cleaning variable p */
  } /*if (f2py_success) of L*/
  /* End of cleaning variable L */
  } /*if (f2py_success) of eps*/
  /* End of cleaning variable eps */
  } /*if (f2py_success) of r_min*/
  /* End of cleaning variable r_min */
  } /*if (f2py_success) of r_c*/
  /* End of cleaning variable r_c */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of lennard_jones ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"lennard_jones",-1,{{-1}},0,(char *)F_FUNC_US(lennard_jones,LENNARD_JONES),(f2py_init_func)f2py_rout_lennard_jones_lennard_jones,doc_f2py_rout_lennard_jones_lennard_jones},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "lennard_jones",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_lennard_jones(void) {
#else
#define RETVAL
PyMODINIT_FUNC initlennard_jones(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = lennard_jones_module = PyModule_Create(&moduledef);
#else
  m = lennard_jones_module = Py_InitModule("lennard_jones", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module lennard_jones (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'lennard_jones' is auto-generated with f2py (version:2).\nFunctions:\n"
"  force,Ep = lennard_jones(r_min,eps,L,r_c,p,N=shape(p,0),d=shape(p,1))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  lennard_jones_error = PyErr_NewException ("lennard_jones.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"lennard_jones");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
